// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChatBoxMessage: typeof import('./src/components/ChatBoxMessage.vue')['default']
    ChatCard: typeof import('./src/components/ChatCard.vue')['default']
    ChatMessageInput: typeof import('./src/components/ChatMessageInput.vue')['default']
    ChatNavbar: typeof import('./src/components/ChatNavbar.vue')['default']
    IconHeroiconsOutlineDotsVertical: typeof import('~icons/heroicons-outline/dots-vertical')['default']
    IconHeroiconsOutlineEmojiHappy: typeof import('~icons/heroicons-outline/emoji-happy')['default']
    IconHeroiconsOutlineMoon: typeof import('~icons/heroicons-outline/moon')['default']
    IconHeroiconsOutlinePaperClip: typeof import('~icons/heroicons-outline/paper-clip')['default']
    IconHeroiconsOutlineSearch: typeof import('~icons/heroicons-outline/search')['default']
    IconHeroiconsOutlineSun: typeof import('~icons/heroicons-outline/sun')['default']
    IconMdiSend: typeof import('~icons/mdi/send')['default']
    MainSidebar: typeof import('./src/components/MainSidebar.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    Searchbar: typeof import('./src/components/Searchbar.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}

export { }
