// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconLogosFacebook: typeof import('~icons/logos/facebook')['default']
    IconLogosGithubIcon: typeof import('~icons/logos/github-icon')['default']
    IconLogosGoogleIcon: typeof import('~icons/logos/google-icon')['default']
    IconMdiBrightness6: typeof import('~icons/mdi/brightness6')['default']
    IconMdiEye: typeof import('~icons/mdi/eye')['default']
    IconMdiEyeOff: typeof import('~icons/mdi/eye-off')['default']
    IconMdiPlusCircle: typeof import('~icons/mdi/plus-circle')['default']
  }
}

export { }
