// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BuilderAuthBaseFooter: typeof import('./components/Builder/Auth/BaseFooter.vue')['default']
    BuilderAuthBaseHeader: typeof import('./components/Builder/Auth/BaseHeader.vue')['default']
    BuilderBaseButton: typeof import('./components/Builder/BaseButton.vue')['default']
    ChatMessageInput: typeof import('./components/ChatMessageInput.vue')['default']
    FormInput: typeof import('./components/Form/Input.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconMdiEye: typeof import('~icons/mdi/eye')['default']
    IconMdiEyeOff: typeof import('~icons/mdi/eye-off')['default']
    PageAuthBaseSection: typeof import('./components/Page/Auth/BaseSection.vue')['default']
    PageAuthBaseWrapper: typeof import('./components/Page/Auth/BaseWrapper.vue')['default']
  }
}

export { }
