// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BuilderAuthBaseFooter: typeof import('./components/Builder/Auth/BaseFooter.vue')['default']
    BuilderAuthBaseHeader: typeof import('./components/Builder/Auth/BaseHeader.vue')['default']
    BuilderBaseButton: typeof import('./components/Builder/BaseButton.vue')['default']
    ChatMessageInput: typeof import('./components/ChatMessageInput.vue')['default']
    FormInput: typeof import('./components/Form/Input.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IconMdiAlert: typeof import('~icons/mdi/alert')['default']
    IconMdiBlockHelper: typeof import('~icons/mdi/block-helper')['default']
    IconMdiBrightness6: typeof import('~icons/mdi/brightness6')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal')['default']
    IconMdiEmoticonNeutral: typeof import('~icons/mdi/emoticon-neutral')['default']
    IconMdiEmoticonOutline: typeof import('~icons/mdi/emoticon-outline')['default']
    IconMdiEye: typeof import('~icons/mdi/eye')['default']
    IconMdiEyeOff: typeof import('~icons/mdi/eye-off')['default']
    IconMdiInformation: typeof import('~icons/mdi/information')['default']
    IconMdiLoading: typeof import('~icons/mdi/loading')['default']
    IconMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IconMdiPaperclip: typeof import('~icons/mdi/paperclip')['default']
    IconMdiSend: typeof import('~icons/mdi/send')['default']
    InfobarAccordion: typeof import('./components/Infobar/Accordion.vue')['default']
    InfobarProfile: typeof import('./components/Infobar/Profile.vue')['default']
    MainAddChat: typeof import('./components/Main/AddChat.vue')['default']
    MainChatBox: typeof import('./components/Main/ChatBox.vue')['default']
    MainNavbar: typeof import('./components/Main/Navbar.vue')['default']
    PageAuthBaseSection: typeof import('./components/Page/Auth/BaseSection.vue')['default']
    PageAuthBaseWrapper: typeof import('./components/Page/Auth/BaseWrapper.vue')['default']
    SidebarChatCard: typeof import('./components/Sidebar/ChatCard.vue')['default']
    SidebarSearchInput: typeof import('./components/Sidebar/SearchInput.vue')['default']
    SidebarTopBar: typeof import('./components/Sidebar/TopBar.vue')['default']
  }
}

export { }
